name: Building containers and deploy to AKS

env:
  REGISTRY_NAME: hoang
  CLUSTER_NAME: ticket-deployment
  CLUSTER_RESOURCE_GROUP: ticket-microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: " Login ACR "
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
  
    - name: "Building auth & push"
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/nvmh0103/auth
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/nvmh0103/auth
      working-directory: ./auth